Enable passing extra K3s flags to k3sUp
datawire/dtest pull request #2
Opened 2021-09-01 11:11 UTC by thallgren

Makes it possible to pass flags to the `k3s server` command
such as `--cluster-domain`

2021-09-10 14:03 UTC, josecv approved these changes

2021-09-14 16:22 UTC, LukeShu requested changes

2021-09-14 16:22 UTC, LukeShu commented on k3s.go
> -		// https://github.com/k3s-io/k3s/pull/3237
Why did you delete this comment?

2021-09-27 14:52 UTC, thallgren commented on k3s.go
> -		// https://github.com/k3s-io/k3s/pull/3237
Good question, I'll add it back.

2021-09-27 16:04 UTC, LukeShu approved these changes

2021-09-27 16:47 UTC, merged